version: 2
updates:
  - package-ecosystem: "npm" # See documentation for possible values
    directory: "/frontend/" # Location of package manifests
    commit-message:
      prefix: "deps: "
    schedule:
      interval: "weekly"
    groups:
      mui:
        patterns:
          - "@mui*"
        update-types:
          - "patch"
      react:
        patterns:
          - "react*"
          - "@types/react*"
        update-types:
          - "minor"
          - "patch"
      eslint:
        patterns:
          - "eslint*"
        update-types:
          - "patch"
      emotion:
        patterns:
          - "@emotion*"
        update-types:
          - "patch"
      joi:
        patterns:
          - "joi"
          - "@types/joi"
        update-types:
          - "minor"
          - "patch"
