version: 2
updates:
  - package-ecosystem: "npm" # See documentation for possible values
    directory: "/" # Location of package manifests
    commit-message:
      prefix: "deps: "
    schedule:
      interval: "weekly"
