version: 2
updates:
  - package-ecosystem: "npm" # See documentation for possible values
    directory: "/frontend/" # Location of package manifests
    commit-message:
      prefix: "deps: "
    schedule:
      interval: weekly
    groups:
      mui:
        patterns:
          - "@mui*"
        update-types:
          - "patch"
      react:
        patterns:
          - "react*"
          - "@types/react*"
        update-types:
          - "minor"
          - "patch"
      eslint:
        patterns:
          - "eslint*"
        update-types:
          - "patch"
      emotion:
        patterns:
          - "@emotion*"
        update-types:
          - "patch"
      joi:
        patterns:
          - "joi"
          - "@types/joi"
        update-types:
          - "minor"
          - "patch"
  - package-ecosystem: nuget
    directory: "/backend/"
    commit-message:
      prefix: "deps: "
    schedule:
      interval: weekly
    groups:
      ef:
        patterns:
          - "Microsoft.EntityFrameworkCore*"
        update-types:
          - "minor"
          - "patch"
      tests:
        patterns:
          - "xunit*"
          - "Microsoft.NET.Test*"
          - "Microsoft.AspNetCore.Mvc.Testing"
          - "FluentAssertions"
          - "coverlet.collector"
          - "NSubstitute"
          - "ReportGenerator"
        update-types:
          - "minor"
          - "patch"
      autofac:
        patterns:
          - "Autofac*"
          - "MediatR.Extensions.Autofac*"
        update-types:
          - "minor"
          - "patch"
      endpoints:
        patterns:
          - "FastEndpoints*"
        update-types:
          - "minor"
          - "patch"
      swashbuckle:
        patterns:
          - "Swashbuckle*"
        update-types:
          - "minor"
          - "patch"
      logging:
        patterns:
          - "Serilog*"
        update-types:
          - "minor"
          - "patch"